import type { Metadata } from "next";
import localFont from "next/font/local";
import '@fortawesome/fontawesome-svg-core/styles.css';
import { config } from '@fortawesome/fontawesome-svg-core'
import "./globals.css";
import {library} from "@fortawesome/fontawesome-svg-core";
import {fas} from "@fortawesome/free-solid-svg-icons";
import {fab} from "@fortawesome/free-brands-svg-icons";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

config.autoAddCss = false;

library.add(fas);
library.add(fab);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="fr">
      <head>
        <meta charSet="UTF-8"/>
        <meta httpEquiv="X-UA-Compatible" content="IE=edge"/>
        <meta httpEquiv="Permissions-Policy" content="interest-cohort=()"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

        <title>CV Viewer</title>

        {/*<link rel="apple-touch-icon" sizes="180x180" href="assets/pictures/favicon/apple-touch-icon.png"/>*/}
        {/*<link rel="icon" type="image/png" sizes="16x16" href="assets/pictures/favicon/favicon-16x16.png"/>*/}
        {/*<link rel="icon" type="image/png" sizes="32x32" href="assets/pictures/favicon/favicon-32x32.png"/>*/}
        {/*<link rel="icon" type="image/png" sizes="192x192" href="assets/pictures/favicon/android-chrome-192x192.png"/>*/}
        {/*<link rel="icon" type="image/png" sizes="512x512" href="assets/pictures/favicon/android-chrome-512x512.png"/>*/}
      </head>
      <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased p-0`}
      >
      {children}
      </body>
      </html>
  );
}
